### ISSUE TITLE
Client crash when typing in server ip

### ISSUE THREAD

**Issue by aulttye** [AllTheMods/ATM-8#630] opened 2023-01-10 01:37 UTC
My client is crashing when i type my server ip in. It crashes once I type v in the ip. I'm on 1.0.8 and has been tested on multiple pc's

**Comment by tmkempster** [comment] 2023-01-10 02:36
Bump - confirmed this as well - makes a big bummer for trying to paste (ctrl + v) IPs

**Comment by aulttye** [comment] 2023-01-10 05:48
> 

(ctrl + v) worked for me. I just couldn't type v as part of the ip. So weird.

**Comment by e-SonOfAnder** [comment] 2023-01-20 22:33
It's being caused by Supplementaries, if you look at the crash log. This is the same issue as https://github.com/AllTheMods/ATM-8/issues/636. If you update Supplementaries to 2.2.35t, it fixes this bug. (It's trying to trigger an in game action when not in game based on the default key bindings for the mod.) You can also try remapping the Quiver Arrow Select action in the key binds, but my testing shows that is unreliable, and will still occasionally trigger the action, even with no key bound.

**Comment by Mitchell5200** [comment] 2023-01-24 14:14
Fixed in 1.0.9

**Closed by Mitchell5200** 2023-01-24 14:14 UTC
Labels: Mod issue, In Dev
