### ISSUE TITLE
Pickaxe not registering as tool

### ISSUE THREAD

**Issue by generalforlife** [AllTheMods/ATM-8#422] opened 2022-12-12 09:24 UTC
updated to 1.0.6 alpha. pickaxe not useable as a tool. when trying to break a block it just says no tool and breaks it as if it was broken with an empty hand.
![ATM 8 bug](https://user-images.githubusercontent.com/58514067/207009036-588b693f-9428-403a-98fd-526376b04f30.png)

**Comment by Mitchell5200** [comment] 2022-12-12 09:56
Duplicate of #421 
Update to 1.0.6b

**Closed by Mitchell5200** 2022-12-12 09:56 UTC
