### ISSUE TITLE
A very interesting and specific situation, resolves into a crash.

### ISSUE THREAD

**Issue by Seroku03** [AllTheMods/ATM-8#1783] opened 2023-12-02 15:54 UTC
So I am trying to move my base from one location to another and moving "Functional Storage" containers is in order.
I move the "Normal" Drawers and the compacting ones with tree slots with no issue. (I use "Sophisticated Storage" Netherite chest with packing tape to put all the drawers inside)
THEN, I try putting the Compacting version with only two slots into the chest. And only opening the player's inventory and hovering the pointer over it (The Compacting version with only two slots), makes the game crash.
I have the Crashing log 
[crash-2023-12-02_10.39.33-client.txt](https://github.com/AllTheMods/ATM-8/files/13536716/crash-2023-12-02_10.39.33-client.txt)
This is a very specific situation and the work around is me taking all the Drawers manually into my new base, but I wanted to share it here because I believe that is important to share.
Salutations to all the amazing team and good day!

**Comment by Mitchell5200** [comment] 2023-12-03 03:10
yep, that's Fixed in functional storage already, either manually update it, or wait for me to clear my backlog and get a pack update complete

Duplicate of #1776

**Closed** 2023-12-18 05:25 UTC
Labels: Bug, duplicate, Mod issue, In Dev, Reported to Dev
