### ISSUE TITLE
AE2 Livingwood Twig Recipe

### ISSUE THREAD

**Issue by JustAnotherGhostName** [AllTheMods/ATM-8#707] opened 2023-01-19 02:47 UTC
ATM version 1.0.8.

When trying to craft a Livingwood twig from Botania in an AE2 terminal using Livingwood (botania:livingwood), it defaults to a recipe to craft 16x sticks, and does not give the option to swap to the Livingwood Twig recipe. See Attached.
![image](https://user-images.githubusercontent.com/122759195/213343757-89b71381-1f9e-4a11-adca-29b3b8be423f.png)

If you try to craft in a more normal crafting interface, such as a Crafting Table On A Stick, it shows the normal recipe by default and an option to swap between then. See attached.

![image](https://user-images.githubusercontent.com/122759195/213343828-4f2e947b-b613-447d-b7fd-c0025f37c632.png)

**Comment by Mitchell5200** [comment] 2023-01-19 02:49
already fixed in dev, this is also a duplicate of #685, Closing

**Closed by Mitchell5200** 2023-01-19 02:49 UTC
Labels: In Dev
