### ISSUE TITLE
GAME CRASH ! 

### ISSUE THREAD

**Issue by G4ming69** [AllTheMods/ATM-8#684] opened 2023-01-16 17:30 UTC
[crash-2023-01-16_18.25.51-server.txt](https://github.com/AllTheMods/ATM-8/files/10428156/crash-2023-01-16_18.25.51-server.txt)
[latest.log](https://github.com/AllTheMods/ATM-8/files/10428159/latest.log)

what kind of shitty mod pack is that that always crashes and you get no help?!

**Comment by Wyvernity** [comment] 2023-01-17 15:34
If you were to check previous issues that are created, you could see I already created an issue post about this. Removing EvilCraft mod solves this issue, but be aware removing it will also make all items and blocks disappear from the mod.

**Comment by Mitchell5200** [comment] 2023-01-18 11:08
Mod at fault identified, and mod dev contacted,
Duplicate of https://github.com/AllTheMods/ATM-8/issues/307, https://github.com/AllTheMods/ATM-8/issues/447, https://github.com/AllTheMods/ATM-8/issues/553, https://github.com/AllTheMods/ATM-8/issues/580, https://github.com/AllTheMods/ATM-8/issues/649

**Closed by Mitchell5200** 2023-01-18 11:08 UTC
Labels: Mod issue
