### ISSUE TITLE
ATM8 Client keeps crashing when playing on a server

### ISSUE THREAD

**Issue by Maikhino** [AllTheMods/ATM-8#1148] opened 2023-03-27 15:22 UTC
When playing on our ATM8 server I seem to be the only one crashing at random intervals. One time I can play for 30 minutes fine and I crash, and then suddenly I keep crashing when joining immediately. Then I have to get lucky I don't crash and can join again.

Things I've tried:

Reinstalling Java

Reinstalling the modpack

Updating graphics driver

(I've allocated 12gb of ram)

This only happens to me and not my friends who are playing with me.

Crash report: https://docs.google.com/document/d/170yktxnGM23yM435cu6J58RJSneP5C9Og7uZhDuktns/edit?usp=sharing

**Comment by Mitchell5200** [comment] 2023-03-27 15:26
Duplicate of https://github.com/AllTheMods/ATM-8/issues/1147, from an hour ago....
as noted there, 1.0.15 of the pack should fix this issue, please report back if it does not

also Duplicate of #923,#930,#933,#943,#944,#949,#959,#980,#985,#988,#990,#993,#999,#1025,#1034,#1036,#1039,#1055,#1059,#1071,#1090 and a few others

**Comment by cns05** [comment] 2023-04-16 23:11
> 

I have had the same exact issue as Maikhino and can confirm that 1.0.15 does not fix the issue

**Comment by TraineeIdgit** [comment] 2023-06-19 08:41
Did this ever get resolved? I too am having similar issues.

https://pste.ch/ituqatixeg.rb

**Comment by Maikhino** [comment] 2023-06-19 21:40
> Did this ever get resolved? I too am having similar issues.
> 
> https://pste.ch/ituqatixeg.rb

Yeah, updating has fixed the issue!

**Closed** 2023-11-05 09:38 UTC
Labels: bug, duplicate, Mod issue, In Dev
