### ISSUE TITLE
Game crashes because of campfires

### ISSUE THREAD

**Issue by shadowskull28** [AllTheMods/ATM-8#1228] opened 2023-04-11 15:00 UTC
A friend of mine would complete a puzzle in one of the Better Desert Temples and a campfire would activate upon puzzle completion and then as of the result the game would then crash because of the campfire entity I'm not sure why but hopefully it gets fixed :(

**Comment by iMahco** [comment] 2023-04-11 20:22
I think this is a duplicate of another ticket that I can't seem to find.. but it was a problem with Hexerei that was fixed in the 0.3.0 update for it.

**Closed** 2023-11-12 10:02 UTC
Labels: bug, question
