### ISSUE TITLE
Issue with Deeper and Darker, Sculk Snapper

### ISSUE THREAD

**Issue by alexanderthedead** [AllTheMods/ATM-8#370] opened 2022-12-01 18:07 UTC
[crash-2022-12-01_03.15.58-server.txt](https://github.com/AllTheMods/ATM-8/files/10135047/crash-2022-12-01_03.15.58-server.txt)

The Sculk Snapper was spawned in by Corail Tombstone's familiar system and causes the server to crash when ticked. This has permanently locked me out of my server unless I delete the area where all of our most important shit is haha.

**Comment by nitrodynamite18** [comment] 2022-12-01 20:57
This is an issue in the mod itself, we know of this and are looking for the cause. Sorry for the inconvenience!

**Comment by Corail31** [comment] 2022-12-02 08:04
@alexanderthedead you can add the entity id as a string in the config 'unhandled_tameable_entities' ;)

**Comment by James103** [comment] 2022-12-06 17:54
With the server stopped, you may be able to kill the offending entity by deleting its corresponding entry at chunk `[12, -9]` in the `r.0.-1.mca` file in the `entities` folder in your world save folder. Afterwards, the server should start up and run without crashing. Check the crash report for the exact region file and chunk to search in.

**Comment by Charismara** [comment] 2023-01-15 08:28
Mod Issue:

#KyaniteMods/DeeperAndDarker#128

**Comment by Kisonu** [comment] 2023-02-06 05:20
Having this issue as well, I was curious... Since this issue is so frequent, is there a known method of preventing the issue or some way to disable the mob from spawning?

**Comment by Mitchell5200** [comment] 2023-07-17 11:38
I've resolved our side, by just disabling the mob in the config
https://github.com/AllTheMods/ATM-8/blob/d746089688f7344a46549fb1dc7ccac0cb7ea3ef/config/deeperdarker.json5#L21

**Comment by Timelord0** [comment] 2023-10-02 01:48
Can confirm it still crashes server as of 1.0.27.

**Comment by Timelord0** [comment] 2023-10-02 01:51
Corral Tombstone allows you to create the sculk snapper, crashing server. Even with above fix.

**Comment by nitrodynamite18** [comment] 2023-10-06 15:26
We are working on a full rewrite of the mod for 1.19.2, including fixing this bug. I am sorry it has taken us so long to fix this bug, there have been issues with former team members and we're all working with the little free time we have. We will have the rewrite released ASAP, I promise.

**Comment by nitrodynamite18** [comment] 2023-10-23 16:28
The 1.19.2 rewrite of the mod has been released and this bug has finally been fixed.

**Closed** 2023-11-05 09:27 UTC
Labels: bug, Mod issue, Reported to Dev
