### ISSUE TITLE
Twilight forest and sophisticated backpack crash

### ISSUE THREAD

**Issue by lharnack** [AllTheMods/ATM-8#680] opened 2023-01-16 01:05 UTC
upon collecting a twilight boss trophy and inserting into a backpack with the compacting upgrade game will crash. This includes both manual insertion or auto pick up. 
https://mclo.gs/atdyVIV

**Comment by enigmaquip** [comment] 2023-01-16 01:15
Duplicate of #657

**Closed by enigmaquip** 2023-01-16 01:15 UTC
