### ISSUE TITLE
I can't play in lan world with friend

### ISSUE THREAD

**Issue by MarlonBEP** [AllTheMods/ATM-8#692] opened 2023-01-17 15:48 UTC
log: https://mclo.gs/W8B22H8

**Comment by MarlonBEP** [comment] 2023-01-17 15:49
![image](https://user-images.githubusercontent.com/75400607/212944885-066d9e05-8f30-4494-b690-0036935e42c4.png)

**Comment by Mitchell5200** [comment] 2023-01-17 15:51
Duplicate of #23 , closing

**Closed by Mitchell5200** 2023-01-17 15:51 UTC
