### ISSUE TITLE
Crashed whilst accessing legacyrandomsource from multiple threads

### ISSUE THREAD

**Issue by Wyvernity** [AllTheMods/ATM-8#580] opened 2023-01-03 00:56 UTC
I keep getting crashes with the same error:
![crash report](https://user-images.githubusercontent.com/110623092/210287960-85c0d302-7048-4c2a-bc54-0d9e641c5c16.png)

It looks like it is related with EvilCraft blood stains. Full crash report can be found here: https://pastebin.com/JWX5405y

I am playing on a singleplayer world.

**Comment by xalixilax** [comment] 2023-01-03 06:11
I also got this crash a lot at random moment. This last one was when I tried to access my Refine storage.
[crash-2023-01-03_01.05.44-server.txt](https://github.com/AllTheMods/ATM-8/files/10334569/crash-2023-01-03_01.05.44-server.txt)

**Comment by MindBrain27** [comment] 2023-01-03 17:01
I have had this 10+ times in the last 12 hours of play time. The crash report seems to mention different mods every time, sometimes it happens looking through JEI, sometimes while running around in caves, and sometimes while just walking around the base.

I noticed the crash report always mentions Twilight Forest somewhere, I have not been there yet.

**Comment by Wyvernity** [comment] 2023-01-03 21:18
> I have had this 10+ times in the last 12 hours of play time. The crash report seems to mention different mods every time, sometimes it happens looking through JEI, sometimes while running around in caves, and sometimes while just walking around the base.
> 
> I noticed the crash report always mentions Twilight Forest somewhere, I have not been there yet.

It is always mentioning about EvilCraft blood stains and blood splash particles for me. The coordinates that are given in the report is in the caves below my base. I will try to remove the mod and play for a while, too see if its actually that mod causing the problems.

**Comment by xalixilax** [comment] 2023-01-04 00:13
I am doing the same. Played for an hour without crash. Might play a bit more tonight

**Comment by MindBrain27** [comment] 2023-01-05 01:11
So to further on this a bit, I turned my particles off and was able to go 12 hours without a crash. I believe the EvcilCraft blood stains as Wyvernity said is correct as I have Undead Trees dripping blood around my base.

**Comment by xalixilax** [comment] 2023-01-17 15:25
I've been playing quite a lot in the past 2 weeks. I can confirm the issue is EvilCraft. After removing it, I stopped having issues. Recently I updated and It didn't stop. When I realize it got added back I deleted it again and didn't crash anymore. The logs are always similar to this but the crash don't always happen at the same time.

**Comment by Mitchell5200** [comment] 2023-01-17 15:31
we've been tracking this internally, and while evilcraft is not the cause of this, we are currently tracking some mods that might be the cause, when we can reproduce the crash that is, only yesterday did someone work out a partially reliable method of causing the LegacyRandomSource crash.

**Comment by Wyvernity** [comment] 2023-01-17 15:43
> we've been tracking this internally, and while evilcraft is not the cause of this, we are currently tracking some mods that might be the cause, when we can reproduce the crash that is, only yesterday did someone work out a partially reliable method of causing the LegacyRandomSource crash.

I don't know what mod actually causes the crash, but I have been able to play for the last 10 days with no crashes after removing EvilCraft. Something is clashing with EvilCraft and making it do weird things I suppose.

**Comment by Mitchell5200** [comment] 2023-01-17 15:50
> > we've been tracking this internally, and while evilcraft is not the cause of this, we are currently tracking some mods that might be the cause, when we can reproduce the crash that is, only yesterday did someone work out a partially reliable method of causing the LegacyRandomSource crash.
> 
> I don't know what mod actually causes the crash, but I have been able to play for the last 10 days with no crashes after removing EvilCraft. Something is clashing with EvilCraft and making it do weird things I suppose.

here's a link to the list of suspect mods https://pastebin.com/raw/4abNreW7 .
the method we have been given was to have some ars source/magelights, and then spam particles, the mahou explosion staff on AOE mode managed to "help" there. it's possible that it's another mod entirely, but as most crashes don't point at anything except minecraft core, or Evilcraft (which the dev claims is not at fault)

**Comment by Wyvernity** [comment] 2023-01-17 16:04
> > > we've been tracking this internally, and while evilcraft is not the cause of this, we are currently tracking some mods that might be the cause, when we can reproduce the crash that is, only yesterday did someone work out a partially reliable method of causing the LegacyRandomSource crash.
> > 
> > 
> > I don't know what mod actually causes the crash, but I have been able to play for the last 10 days with no crashes after removing EvilCraft. Something is clashing with EvilCraft and making it do weird things I suppose.
> 
> here's a link to the list of suspect mods https://pastebin.com/raw/4abNreW7 . the method we have been given was to have some ars source/magelights, and then spam particles, the mahou explosion staff on AOE mode managed to "help" there. it's possible that it's another mod entirely, but as most crashes don't point at anything except minecraft core, or Evilcraft (which the dev claims is not at fault)

I think it is very unlikely that the crash is caused by world gen legacy sources since it also happens while just AFK'ing in loaded chunks. Just a thought tho, anything could be the issue

**Comment by Mitchell5200** [comment] 2023-01-18 10:27
Mod at fault identified, and mod dev contacted, 
Duplicate of #307, #447, #553, #580, #649

**Closed** 2023-01-21 15:30 UTC
Labels: Mod issue
