### ISSUE TITLE
KubeJS Server_skript not working

### ISSUE THREAD

**Issue by Sl0ter** [AllTheMods/ATM-8#123] opened 2022-10-17 15:26 UTC
Every Recipe with #Forge:***** won't show anything on a server.
on client it works.
Quarry Workbanch has no recipe on a server but in single player it works

**Comment by Sl0ter** [comment] 2022-10-17 20:07
I made a fix for every recipe.

the Path (important) is Minecraftserver-folder/kubejs/mods

override every folder in it with all what is in the ZIP
[mods.zip](https://github.com/AllTheMods/ATM-8/files/9804137/mods.zip)

**Comment by enigmaquip** [comment] 2022-10-17 20:17
Duplicate of #111 and also fixed by updating kubejs, which we have done in v1.0.4

**Closed by enigmaquip** 2022-10-17 20:17 UTC
