### ISSUE TITLE
KubeJS Error parsing recipe 

### ISSUE THREAD

**Issue by Blackscorp66** [AllTheMods/ATM-8#1766] opened 2023-11-13 00:20 UTC
Hello,

I have an error on ATM 8 :

[minecraft/MinecraftServer]: 1) Error parsing recipe biggerreactors:compat/mekanism/crushing/crusher_deepslate_uranium_ingot[mekanism:crushing]: {"type":"mekanism:crushing","conditions":[{"modid":"mekanism","type":"forge:mod_loaded"}],"input":{"ingredient":{"item":"biggerreactors:deepslate_uranium_ingot"}},"output":{"item":"alltheores:uranium_dust","count":1}}: com.google.gson.JsonSyntaxException: Unknown item 'biggerreactors:deepslate_uranium_ingot'

What should I do to fix this? It's making the game slower sadly

Edit : For info, I have reloaded the game and restarted it to try. But nothing seems to work.

Thank you

**Comment by gizmocodes** [comment] 2023-11-19 20:34
It looks like I screwed up the recipe JSON when I was creating it a few months ago, and it went unnoticed until now. I'll get that fixed here in Bigger Reactors in a little bit. Sorry about that!

**Comment by gizmocodes** [comment] 2023-11-20 03:48
Update 0.6.0-beta.6.4 for 1.19.2 and 0.6.0-beta.10.4 for 1.20.1 have been released on GitHub and CurseForge. Please give the appropriate jar a try and make sure it fixes the issue. If it does, then should be good to include in the next ATM8 update.

**Comment by Mitchell5200** [comment] 2023-11-20 04:08
TY Gizmo, will do

**Comment by Mitchell5200** [comment] 2023-11-20 04:55
Confirmed fixed, will be included in 1.0.29

**Closed** 2023-12-18 05:26 UTC
Labels: Bug, In Dev
