### ISSUE TITLE
error involving Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by BLU13** [AllTheMods/ATM-8#746] opened 2023-01-24 01:46 UTC
I have gotten this crash message a lot recently and I don't know why, I've tried looking it up but everyone says its connected texture issue but I don't have any connect texture things. here is the crash log, I'm assuming you would want that and would know more about the stuff it says than I do. 
[crash-2023-01-23_19.32.53-server.txt](https://github.com/AllTheMods/ATM-8/files/10485686/crash-2023-01-23_19.32.53-server.txt)

**Comment by Mitchell5200** [comment] 2023-01-24 01:51
Duplicate of #307, #447, #553, #580, #649 , will be fixed in the next update

**Comment by Mitchell5200** [comment] 2023-01-24 14:12
Fixed in 1.0.9

**Closed by Mitchell5200** 2023-01-24 14:12 UTC
Labels: duplicate, Mod issue
