### ISSUE TITLE
Equipped energetic angel ring causes an internal server error and wont allow affected user to login

### ISSUE THREAD

**Issue by tpjham** [AllTheMods/ATM-8#114] opened 2022-10-16 17:56 UTC
As per title, I shift right-click equipped an empty energetic angel ring on my hosted server and can no longer login to the server at all. 
I can see an Internal Server Error being thrown in the server console:

[Link to server latest.log from the error](https://mclo.gs/ZUevEzL)

**Comment by DenisMasterHerobrine** [comment] 2022-10-18 16:01
Thanks for the information, fixed in v2.1.4 of Angel Ring 2.
The issue is related to a warning when you're out of FE and due to another minor breaking change it kicks the player since the method for Angel Ring 2 for 1.19 build used was removed on Forge side.

**Closed** 2023-01-18 14:30 UTC
