### ISSUE TITLE
witch drying rack

### ISSUE THREAD

**Issue by sassysarah01987** [AllTheMods/ATM-8#1317] opened 2023-05-01 13:10 UTC
the witch drying rack duplicates any item you place on it

**Comment by Mitchell5200** [comment] 2023-05-01 13:13
Yes, known, reported, we have a temp fix indev for the next pack update, until the dev fixes it
Duplicate of https://github.com/AllTheMods/ATM-8/issues/1307 ,https://github.com/AllTheMods/ATM-8/issues/1290
Hexerei issue post https://github.com/JoeFoxe/Hexerei-1.19/issues/36

**Closed by Mitchell5200** 2023-05-01 13:13 UTC
Labels: bug, duplicate, Mod issue, In Dev, Reported to Dev

**Comment by HumdrumPanic** [comment] 2023-10-25 04:33
There were a lot of unspecified bugfixes for Hexerei in its version 3.0.

(from hexerei changelog: "Fixed nearly all of the bugs on the bug tracker, so if you run into another unintended bug please put it in the issues.")

Atm 8 1.20 looks to have updated hexerei to 3.2.2... so it may have been fixed with any version past that.

ATM8 still has the temp script installed and recipes locked by default. You can easily disable those yourself by deleting the kubejs scripts in order to test it if you don't want to wait.

Although the recipe lock script for the racks is in the same script file as the securitycraft project dupe bug so you might have to edit out the specific lines for the drying racks as I think the projector is still bugged.
