### ISSUE TITLE
The QuarryPlus Workbench Plus is not craftable

### ISSUE THREAD

**Issue by Ferro-Giconi** [AllTheMods/ATM-8#116] opened 2022-10-16 19:50 UTC
When checking in JEI, the recipe is blank.

**Comment by tpjham** [comment] 2022-10-16 19:58
Works if you check on singleplayer, caused by #111

**Comment by Mitchell5200** [comment] 2022-10-17 06:37
As stated in #111 Known Issue, only affects servers currently. Closing this Duplicate.

**Closed by Mitchell5200** 2022-10-17 06:37 UTC

**Comment by Sl0ter** [comment] 2022-10-17 20:14
i made a fix here for now. #123
