### ISSUE TITLE
[1.0.6b] Pickaxe not displaying mining level properly

### ISSUE THREAD

**Issue by GeneralVonGelre** [AllTheMods/ATM-8#423] opened 2022-12-12 09:46 UTC
![Screenshot 2022-12-12 104437](https://user-images.githubusercontent.com/8538414/207013577-89f89dca-8617-48c1-a868-785a470b9700.png)

The tooltip fails to realise the pick being used is of the correct mining level for mining a certain ore. If the ore is mined the drop works correctly, so it is a display issue only.

**Comment by Mitchell5200** [comment] 2022-12-12 09:56
Duplicate of #421 
Update to 1.0.6b

**Comment by Mitchell5200** [comment] 2022-12-12 09:57
sorry different issue, re-opening

**Closed** 2023-03-16 04:11 UTC
