### ISSUE TITLE
Crash- Evilcraft/Axolotl Interaction

### ISSUE THREAD

**Issue by Offtheblock** [AllTheMods/ATM-8#447] opened 2022-12-18 08:19 UTC
[crash-2022-12-18_21.00.13-server.txt](https://github.com/AllTheMods/ATM-8/files/10253406/crash-2022-12-18_21.00.13-server.txt)
From what little I can understand(which is very little), my game crashes after an axolotl walks onto an evilcraft bloodstain.
The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit code -1
Any help/fix appreciated.
-OTB

**Comment by Mitchell5200** [comment] 2022-12-18 09:08
Please forward this report to the Evilcraft dev, https://github.com/CyclopsMC/EvilCraft/issues  as it seems to be an active issue there

**Comment by DerpyFrood0421** [comment] 2022-12-21 20:38
I think this is the same issue as this: https://github.com/CyclopsMC/EvilCraft/issues/954

**Comment by Mitchell5200** [comment] 2023-01-18 10:28
Evilcraft has closed their issue as solved, however another mod is still causing issues, that will be solved soon.

Mod at fault identified, and mod dev contacted, 
Duplicate of #307, #447, #553, #580, #649

**Closed by Mitchell5200** 2023-01-18 10:28 UTC
