### ISSUE TITLE
Multiplayer trouble

### ISSUE THREAD

**Issue by Rongorn1** [AllTheMods/ATM-8#716] opened 2023-01-20 20:07 UTC

**Comment by Rongorn1** [comment] 2023-01-20 20:11
Hi! I have a problem connecting to my friend's world. Every time we connect we see the same error message :Hi! I have a problem connecting to my friend's world. Every time we connect we see the same error message : "Internal Exception: io.netty.handler.code.EncoderException:ava.lang.MullFointerException"

How can we fix it? We reinstalled java, we reinstalled the modpack, we did everything we could think of.

**Comment by Rongorn1** [comment] 2023-01-20 20:11
Pls, help us.

**Comment by Mitchell5200** [comment] 2023-01-21 01:56
If you're using Open to LAN, that's a duplicate of #23, We have finally traced the exact cause of this issue and will have it fixed in 1.0.9

**Closed by Mitchell5200** 2023-01-21 01:56 UTC
Labels: duplicate, Mod issue
