### ISSUE TITLE
CTD after about a minute loaded into game

### ISSUE THREAD

**Issue by Kaiagarro** [AllTheMods/ATM-8#135] opened 2022-10-18 19:24 UTC
With or without shaders I CTD. I have played several hours without having any issue but noticed it after I started collecting Dark Ore from Evilcraft.
[crash-2022-10-18_12.14.53-client.txt](https://github.com/AllTheMods/ATM-8/files/9814429/crash-2022-10-18_12.14.53-client.txt)

**Comment by NicoVIII** [comment] 2022-10-19 14:01
The crash log looks like this is caused by the same issue described in #126.

**Comment by whatthedrunk** [comment] 2022-10-22 01:01
Fixed in today's update thanks.

**Closed by whatthedrunk** 2022-10-22 01:01 UTC
