### ISSUE TITLE
Stone button no longer craftable because of gregtech

### ISSUE THREAD

**Issue by smerecz** [AllTheMods/ATM-8#1667] opened 2023-08-21 16:28 UTC
Gregtch's recipe overrides the recipe for stone button and now only make stone dust

**Comment by Mitchell5200** [comment] 2023-08-22 08:24
Wrong repo, and Duplicate of https://github.com/AllTheMods/ATM-9/issues/276.

**Closed by Mitchell5200** 2023-08-22 08:24 UTC
