### ISSUE TITLE
Nice ModPack-NOT !

### ISSUE THREAD

**Issue by G4ming69** [AllTheMods/ATM-8#708] opened 2023-01-19 08:37 UTC
Since I always had crashes, I removed the EvilCraft mod because it was recommended to me. only then there was kubjs error wolrd gen script error......, and now i can't build the ATM star anymore because the crafting recipe for the Pulsating Black Hole just isn't there anymore!

**Comment by Mitchell5200** [comment] 2023-01-19 13:06
The crash LegacyRandomSource is not caused by Evilcraft, the actual cause of the issue has been identified and is now being fixed. Once we have that and a couple of other things sorted, Update 1.0.9 will be released.

The following are all of the related issues regarding this crash #307, #447, #553, #580, #649, #648, #139, #30.

**Closed by Mitchell5200** 2023-01-19 13:06 UTC
