### ISSUE TITLE
Game crashes sometimes on inventory open

### ISSUE THREAD

**Issue by mspen002** [AllTheMods/ATM-8#136] opened 2022-10-18 21:50 UTC
[2022-10-18-5.log](https://github.com/AllTheMods/ATM-8/files/9815337/2022-10-18-5.log)

Game says "Saving World" before crashing. I'm playing on a server, so I don't know why it would do that, and it's not generating any specific error logs, just these logs that show up after.

Game crashes when I open my inventory, I don't think I have many/any mod specific items in my inventory, it doesn't always crash during the open, sometimes it's fine for a while, then sometimes it crashes instantly, I was able to move a bunch of items one time, then other times it would crash immediately.

**Comment by AlexisTheCultLeader** [comment] 2022-10-19 01:10
Judging by your log, it seems you and I are having the same issue. it is caused by Patchouli. For whatever reason, Patchouli needs to be downgraded to the previous version. Version 77 crashes when any tooltip for an Ars Nouveau (and possibly others) item in the inventory is scrolled over. I've included my own crash report for you to glance at. The ATM team will have to release an update to fix the error. In the meantime, you can try manually removing or replacing Patchouli in the mod folder but beware that this can cause issues with launching ATM in CurseForge.

[crash-2022-10-18_08.58.44-client.txt](https://github.com/AllTheMods/ATM-8/files/9815983/crash-2022-10-18_08.58.44-client.txt)

**Comment by mspen002** [comment] 2022-10-19 13:59
@AlexisTheCultLeader unfortunately for me, I was heavily focused on Ars Nouveau stuff, so it'd be nearly impossible to avoid... :( but thank you for the heads up, I'll probably just have to wait until a new patch fixes it.

**Comment by NicoVIII** [comment] 2022-10-19 14:02
It looks like this is caused by the same issue described in #126.

**Comment by AlexisTheCultLeader** [comment] 2022-10-19 14:28
@mspen002 They typically are pretty quick to fix things like this, and with our logs included and me pointing out the exact issue it shouldn't be a very long wait :) Hopefully that is reassuring. In the meantime, I strongly recommend RLCraft if you're looking for a challenging modpack with magic in it. Alternatively, try "ATM 7" or "ATM 7 - To The Sky" ( I think that's what it's called). Those packs will keep you plenty busy, I assure ya :P

**Comment by whatthedrunk** [comment] 2022-10-22 01:02
Fixed in today's update thanks.

**Closed by whatthedrunk** 2022-10-22 01:02 UTC
