### ISSUE TITLE
occutltism is makes my game crash immediately when im in creative and open the inventory

### ISSUE THREAD

**Issue by ClickityChicken** [AllTheMods/ATM-8#1785] opened 2023-12-10 01:11 UTC
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry Object not present: occultism:spawn_egg/possessed_ghast

**Comment by Avalon1892** [comment] 2023-12-12 13:29
same. ATM9

**Comment by Mitchell5200** [comment] 2024-01-07 05:42
Cannot reproduce in ATM8 1.1.0, Closing without full logs.

**Closed by Mitchell5200** 2024-01-07 05:42 UTC
