### ISSUE TITLE
1.0.20 Update with Hostile Neural Networks 4.1.0 broke existing Creeper/Ghast Data Models

### ISSUE THREAD

**Issue by marco3102** [AllTheMods/ATM-8#1486] opened 2023-06-20 19:46 UTC

**Comment by marco3102** [comment] 2023-06-21 17:55
I'd rather not risk changing the game version on my server again, it caused a lot of unrelated problems last time.
I checked single player with the same version and it worked just fine.
The Mob Data Models I was using werent in the JER Items Tab and the ones that were existing had a constantly changing name to imply that an error occured.

The Amount of Missing Data Models were about half.

**Comment by PersiflageTheNinth** [comment] 2023-06-21 18:34
Creeper and Ghasts weren't broken, they were made to support more mobs counting as a kill, in the Deep Learner screen it's changing because it's slowly cycling through all the allowed mobs for that data model, if you hover over the model with shift held down you can see all the variant options that apply
![image](https://github.com/AllTheMods/ATM-8/assets/128710797/393f0dc3-3233-4833-8eac-d5fd89860b15)

**Comment by coldbru7** [comment] 2023-06-23 13:24
I apologize for not being able to send a photo i’m out of the house currently, however I believe the same thing is happening to me, in my case some of the data models don’t “exist” anymore, wither, piglin, ender dragon, etc. And when you right click the mob to create a data model it gives an “error” data model.

**Comment by Trnrr** [comment] 2023-07-08 20:19
I believe I'm having a similar issue with certain data models not appearing. We were previously on version 1.0.19b and upgraded our server to 1.0.20 and then to 1.0.21b. When on the server we can not see half the data models (Piglich, ender dragon, wither, ghast, etc). Like coldbru7, when we right click a mob that should exist we get an error data model that is unusable. When in singleplayer, we can see/use the all data models. Were more models added in one of the 1.0.2x updates? I'm wondering if our server host didn't property update the modpack. From what we can tell, everything else is working as intended.

**Comment by Shadows-of-Fire** [comment] 2023-07-12 01:10
A sizeable amount of models were added to HNN natively in 4.1.0 - however, based on https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/31 and https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/32 it seems like there are difficulties migrating to the new models (as ATM8 used to ship models with the same ID), which is the root of the problem.

As per this comment https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/32#issuecomment-1620930447 from @LordCorellon, it may be resolved by performing a fresh clone of the ATM8 KubeJS folder.

**Closed** 2023-11-12 12:07 UTC
