### ISSUE TITLE
1.19: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by McNasties** [AllTheMods/ATM-8#307] opened 2022-11-21 15:18 UTC
IllegalStateException randomly. Freezes, saves game, and closes.
[crash-2022-11-21_10.11.44-client.txt](https://github.com/AllTheMods/ATM-8/files/10057716/crash-2022-11-21_10.11.44-client.txt)

**Comment by roguethedev** [comment] 2022-11-29 17:11
Hello I'm having similar error. This error occurs just randomly, sometimes take hours or maybe minutes. 

I'm playing Singleplayer at Mac M1 Pro 16gb using Curse Forge app to launch, I didnt change nothing at the modpack files

Description: Accessing LegacyRandomSource from multiple threads

[crash-2022-11-29_13.52.50-client.txt](https://github.com/AllTheMods/ATM-8/files/10115407/crash-2022-11-29_13.52.50-client.txt)

[crash-2022-11-29_13.39.18-server.txt](https://github.com/AllTheMods/ATM-8/files/10115416/crash-2022-11-29_13.39.18-server.txt)

I don't know if is the map corrupt, or if the Mac its not recomend to play ATM, any help will be welcome.

**Comment by NoMoreStars** [comment] 2022-12-19 23:59
Just got a [similar crash](https://pastebin.com/K4dMsM4N) as well

**Comment by Ninjawolf0007** [comment] 2022-12-22 02:34
This is likely the same bug as [here](https://github.com/CyclopsMC/EvilCraft/issues/954) which has been fixed by the EvilCraft mod author but the pack has not updated yet. You can manually change the pack and decide to upgrade or downgrade EvilCraft if you so choose and that should help.

**Comment by Ninjawolf0007** [comment] 2022-12-24 23:04
I thought this was related to an EvilCraft issue, but after the update to version 1.0.7 of ATM8, I'm also seeing this crash seemingly unrelated to a specific mod from what I can gather.
[crash-2022-12-24_14.58.42-client.txt](https://github.com/AllTheMods/ATM-8/files/10299247/crash-2022-12-24_14.58.42-client.txt)

**Comment by alekthefirst** [comment] 2022-12-27 23:47
I believe this is caused by Supplementaries which in [this commit here](https://github.com/MehVahdJukaar/Supplementaries/commit/2fe094c8e936bdd21e0694ab7b2233f0d627bca1) 
common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/blocks/PedestalBlock.java:152
introduces a piece of code that [apparently is thread unsafe](https://github.com/team-abnormals/savage-and-ravage/issues/119) and can cause crashes like this

**Comment by TelepathicGrunt** [comment] 2022-12-29 21:03
@alekthefirst No, the block's use method is ran only on server where it is safe to use level.random. The issue is someone is using the level's random on an off thread instead of server thread. Common places people accidentally misuse the wrong random is during worldgen or within entity constructors/finalizeSpawn mehods which also runs on off thread during worldgen. Nothing in that Supplementaries commit stands out.

**Comment by TelepathicGrunt** [comment] 2022-12-29 21:06
EvilCraft did make a change in dev to fix the randomsource crash as they seemed to have narrowed down themselves as a potential cause of it: https://github.com/CyclopsMC/EvilCraft/commit/b03ed5eb28decaf0f8e60514738e05ee35618bce

**Comment by Mitchell5200** [comment] 2023-01-18 10:26
Mod at fault identified, and mod dev contacted, 
Duplicate of #307, #447, #553, #580, #649

**Comment by Mitchell5200** [comment] 2023-01-24 14:15
Fixed in 1.0.9

**Closed by Mitchell5200** 2023-01-24 14:15 UTC
Labels: Mod issue
