### ISSUE TITLE
Dank storage crashing game on server 

### ISSUE THREAD

**Issue by hazzmatfaizon** [AllTheMods/ATM-8#759] opened 2023-01-24 21:28 UTC
whenever i try to move or even breath near the dank it crashes my game and gives me exit code one. i have attached my crash log and prey my danky boy came be fixed
[crash-2023-01-24_15.25.17-client.txt](https://github.com/AllTheMods/ATM-8/files/10494156/crash-2023-01-24_15.25.17-client.txt)

**Comment by AfkUserMC** [comment] 2023-01-24 21:38
Crash Report in MCLO.GS:
https://mclo.gs/YEIINSR

**Comment by Numeritxs** [comment] 2023-01-24 22:05
Can reproduce.
Also happens when I try to see a recipe from JEI while having the dank in my inventory.
Using 'Q' to drop the dank from the inventory also crashes the game. 
I'm playing on a private server.

MCLO.GS attachment:
https://mclo.gs/ZjqIMGI

**Comment by hazzmatfaizon** [comment] 2023-01-24 22:51
rip my danky boii 
![Screenshot 2023-01-24 164954](https://user-images.githubusercontent.com/83434939/214438741-586c8acf-889b-4e6d-a16b-abf7bbcd7634.png)

**Comment by SerenityFire** [comment] 2023-01-25 19:21
Yes can confirm the crash.
`The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129880_(net.minecraft.resources.ResourceKey)" because "tfar.dankstorage.DankStorage.instance.server" is null`

**Comment by Mitchell5200** [comment] 2023-01-27 04:15
Fixed by the mod dev, we'll have this updated in an upcoming update "soon"

**Comment by Mitchell5200** [comment] 2023-01-30 15:16
Fixed in 1.0.10

**Closed by Mitchell5200** 2023-01-30 15:16 UTC
Labels: bug, Mod issue, In Dev
