### ISSUE TITLE
1.0.14 - Crystall Staff Acceleration not saving

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-8#1132] opened 2023-03-24 18:45 UTC
Hi.

Every time I change world  in my game, all machines that I have boosted with cryystal staff acceleration from roots are not saving and lose their effects.

**Comment by fkempf78** [comment] 2023-03-27 11:08
This is a feature of roots, it should only work for a limited time. So the bug is now fixed, the acc. should only last for some  time.

**Comment by Mitchell5200** [comment] 2023-03-27 11:11
Closing as working as intended

**Closed as completed by Mitchell5200** 2023-03-27 11:11 UTC
