### ISSUE TITLE
Client crash when miss-clicking a quest's detail box in the quest tab.

### ISSUE THREAD

**Issue by maharveys** [AllTheMods/ATM-8#401] opened 2022-12-08 01:26 UTC
What the launcher has to say about the crash, "The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Style.m_131182_()" because 'style' is null."

What the I have to say about the crash:
This bug can be recreated by going into the game and opening up the quest tab (top right 'book' icon in inventory), then clicking on a quest icon (The one I selected was the first quest for Refined Storage), and lastly clicking on the border of the popup that details what the quest is about. This happened when I miss-clicked to the left of the pin button.

Crash report below.
[crash-2022-12-07_20.02.20-client.txt](https://github.com/AllTheMods/ATM-8/files/10181328/crash-2022-12-07_20.02.20-client.txt)

**Comment by CasterMx13** [comment] 2022-12-17 23:12
This same crash has been plaguing me; Almost worth it to not even do the quests.

**Comment by alfredggttv** [comment] 2022-12-26 02:49
This seems to have been fixed in the latest version of ATM. I cannot reproduce the issue.

**Closed by alfredggttv** 2022-12-26 02:49 UTC
