### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by RickyGeo** [AllTheMods/ATM-8#30] opened 2022-09-22 12:05 UTC
[crash-2022-09-22_13.00.42-client.txt](https://github.com/AllTheMods/ATM-8/files/9625456/crash-2022-09-22_13.00.42-client.txt)

always crash

**Comment by Mitchell5200** [comment] 2023-01-18 14:22
Mod at fault identified, and mod dev contacted, 
Duplicate of #307, #447, #553, #580, #649

**Closed by Mitchell5200** 2023-01-18 14:22 UTC
Labels: Mod issue
