### ISSUE TITLE
Fix Bundle and Sophisticated Storage/Backpacks duplication glitch

### ISSUE THREAD

**Issue by CyrolX** [AllTheMods/ATM-8#375] opened 2022-12-02 17:46 UTC
There is a glitch involving Bundles and Backpacks using the Stack upgrades from Sophisticated Storage/Backpacks. When putting bundles into a Sophisticated Storage Chest or a Sophisticated Backpacks Backpack, which contain any Tier of Stack upgrade, the bundles stack as expected.
There is the option to put an item into a portable storage container (like bundles) by right clicking the storage container in the inventory while holding said item with the mouse.

This is the source of the glitch. When Bundles are stacked (which they normally cant be) and the user tries to put an item they hold with their mouse into the Bundle using right click, it will be put into all the bundles on the stack, leading it to be duplicated in an amount equal to the size of the stack. The maximum amount of stacked bundles is 16 using the Netherite Stack upgrade, meaning an item can be duplicated 16-fold when put into a bundle.

The duplicated items are no ghost items and persist through relogging and restarting.

Following are some screenshots describing the steps for reproduction in detail:

**Step 1:** Have any Sophisticated Storage Chest/Sophisticated Backpacks Backpack allowing for upgrades to be installed, and install any suitable Stack upgrade. In my case its a Netherite Backpack with a Tier 4 Stack upgrade.
![2022-12-02_18 31 42](https://user-images.githubusercontent.com/31181255/205352096-2b9c8526-eceb-40a6-8622-cd398d42d7f3.png)

**Step 2:** Put some Bundles into the Chest/Backpack so they stack. Sometimes Bundles don't want to stack, which is fixed by putting an item into the Bundle and taking it out again.
![2022-12-02_18 32 12](https://user-images.githubusercontent.com/31181255/205352444-65642d7f-abfa-4f78-b567-cf70222d2ac0.png)

**Step 3:** Pick any item you want to duplicate and hold it with your mouse. In my case I took my Mythic Allthemodium Sword.
![2022-12-02_18 32 28](https://user-images.githubusercontent.com/31181255/205352636-8aa692bc-b3d8-4aee-a69f-3a4c4528bccb.png)

**Step 4:** With the item in hand, hover over a Bundle stack and right click it. The item should now be in the Bundle stack.
![2022-12-02_18 32 40](https://user-images.githubusercontent.com/31181255/205352801-7fbd5088-3f48-439b-a939-12c3f95c3af8.png)

**Step 5:** Shift + Right Click on the Bundle Stack to remove a Bundle from the Stack. As you can see, the Bundle Stack is still shown as full, and so is the Bundle I took from the Stack. It contains my Mythic Allthemodium Sword.
![2022-12-02_18 32 52](https://user-images.githubusercontent.com/31181255/205352994-1cd8e347-42cb-45af-a286-c2319bf1c296.png)

**Step 6 and 7:** Repeat Step 5 for all the Bundles in the Stack. Now, by scrolling down, retrieve the item(s) from each Bundle. The result of my duplication is shown here:
![2022-12-02_18 33 31](https://user-images.githubusercontent.com/31181255/205353283-5b580de3-4f17-4976-90d7-0beafbaf994d.png)

These are all Mythic Allthemodium Swords of the same kind and as such are technically stackable, which can be seen here:
![2022-12-02_18 35 22](https://user-images.githubusercontent.com/31181255/205353493-2b6414e7-3156-4fb4-b905-5e096082af13.png)

**Comment by P3pp3rF1y** [comment] 2022-12-02 21:53
So the stashing of items into bundles is a Quark functionality so by default with just sophisticated mods you are not able to do this (and quark should really be checking that it is stashing items into a container stack of 1 as the same thing will be doable with any other mod that provides this kind of stacking capability and has gui). But in the latest version of sophisticated backpacks/storage the config default for stack upgrade automatically bans stacking of bundles and shulker boxes in sophisticated inventories.

**Comment by Mitchell5200** [comment] 2022-12-03 07:17
After some more testing, it seems that the auto sort seems to be able to bypass the stackables blacklist, but this does not occur in a install with just Sophisticated storage and backpacks.
 I believe a different auto sort mod is interfering here too, i'll look into that further when i can, but in the meantime i'll just blacklist bundles from backpacks, and @P3pp3rF1y can i bug you about getting an insert blacklist option for the storage side of the mod?

**Comment by P3pp3rF1y** [comment] 2022-12-03 21:34
@Mitchell5200 I assume you have done the testing with the latest versions, right? Just checking because I made some fixing in stacking functionality. 
What way have you used to insert the items that they would stack? Just a simple hopper? 
I haven't had a chance to test in dev yet, but just looking at the code the check is properly made when inserting as well.

**Comment by ClintonOrdonez** [comment] 2022-12-04 00:38
I checked earlier today, and the current version of ATM8 does not contain the most recent versions of the Sophisticated series.

**Comment by Mitchell5200** [comment] 2022-12-05 13:07
> 

yeah... so when i was testing, i was using the latest version, but when i was doing pack testing in 1.0.4, that was not latest, i have retested in 1.0.5 dev and have confirmed it to be working correctly now.

Closing as this will be fixed in the Next Pack release

**Closed by Mitchell5200** 2022-12-05 13:07 UTC
