### ISSUE TITLE
Rubber seed not craftable

### ISSUE THREAD

**Issue by niggelasso** [AllTheMods/ATM-8#1346] opened 2023-05-08 11:29 UTC
the rubber seed of mystical agriculture is not craftable, recipe only says "Empty Tag: forge:rubber"

**Comment by Mitchell5200** [comment] 2023-05-08 11:34
Duplicate of  #278,#468,#844

**Comment by Mitchell5200** [comment] 2023-11-05 09:28
Fixed, closing

**Closed by Mitchell5200** 2023-11-05 09:28 UTC
Labels: bug, duplicate
