### ISSUE TITLE
ATM8 - DankStorage Crash

### ISSUE THREAD

**Issue by Itnarui** [AllTheMods/ATM-8#795] opened 2023-01-28 23:17 UTC
Hello, i have a server with some friends, but after updating to version 1.0.9 we started crashing only when hovering the mouse on the DankStorage.

here it is the pastbin of the crash log
`https://pastebin.com/BwR9sRru`

all and any help would be gladly acepted 😄

**Comment by AfkUserMC** [comment] 2023-01-29 18:35
Duplicate of #759

**Comment by Mitchell5200** [comment] 2023-01-30 15:25
Danks Fixed in 1.0.10

**Closed by Mitchell5200** 2023-01-30 15:25 UTC
