### ISSUE TITLE
My brother cannot connect through LAN. 

### ISSUE THREAD

**Issue by JoeMamma421** [AllTheMods/ATM-8#631] opened 2023-01-10 03:50 UTC
It says "player joined" and then "player left" instantly. The new ATM8 update just released and the problem is still persistent. I havent found ANY solutions online and anything ive tried myself hasent worked either. Please help!

**Comment by BastionNtB** [comment] 2023-01-11 03:18
Need some details.

Dedicated server host? Or singleplayer opened to LAN? OS of both of you? version of ATM8?

**Comment by AfkUserMC** [comment] 2023-01-11 03:19
this is a known issue.

**Comment by Mitchell5200** [comment] 2023-01-11 03:21
Duplicate of #23 , Closing

**Closed by Mitchell5200** 2023-01-11 03:21 UTC
Labels: duplicate
