### ISSUE TITLE
Netherite Furnace Appears to cause crashes

### ISSUE THREAD

**Issue by spaceXrace** [AllTheMods/ATM-8#710] opened 2023-01-19 10:14 UTC
[crash-2023-01-19_11.00.35-server.txt](https://github.com/AllTheMods/ATM-8/files/10455740/crash-2023-01-19_11.00.35-server.txt)

**Comment by Mitchell5200** [comment] 2023-01-19 10:19
Duplicate of issue #514, already reported to dev https://github.com/Qelifern/IronFurnaces/issues/143

**Closed by Mitchell5200** 2023-01-19 10:19 UTC
Labels: duplicate, Mod issue
