### ISSUE TITLE
 internal error (java.lang.unsupportedoperationexception) : failed to get registry access. this is a bug. When trying to join server

### ISSUE THREAD

**Issue by Mariozah21** [AllTheMods/ATM-8#976] opened 2023-02-28 09:43 UTC

**Comment by Mitchell5200** [comment] 2023-02-28 10:07
Duplicate of #973 , Under investigation

**Comment by Mitchell5200** [comment] 2023-02-28 12:42
Issue solved 1.0.13 is now pending Curse approval for release

**Comment by Mitchell5200** [comment] 2023-02-28 13:52
CF approved, Closing

**Closed by Mitchell5200** 2023-02-28 13:52 UTC
Labels: bug, duplicate, Mod issue, In Dev
