### ISSUE TITLE
Refined Storage Exporter/Importers cant change Redstone Signal Mode in GUI

### ISSUE THREAD

**Issue by marco3102** [AllTheMods/ATM-8#1443] opened 2023-06-13 00:56 UTC
Ive screened the Refined Storage Github and found these
#(https://github.com/refinedmods/refinedstorage/issues/2847)
#https://github.com/refinedmods/refinedstorage/issues/2855

It seems to be related to the pack as in previous Instances of ATM a pack update seemed to fix this issue so Im hoping this issue is known and easily fixable.

**Comment by MCPorky** [comment] 2023-07-09 20:28
This is unlikely to be fixed.
The cause of this issue is actually Cable Tiers.

See [here](https://github.com/starforcraft/Cable-Tiers/issues/34#issuecomment-1627718193)

I would suggest removing the mod unless you're happy to workaround it.

**Comment by AntiairPalme** [comment] 2023-07-22 00:18
Any update removing CableTiers as the offical Dev sayed it wont be fixed in 1.19?

[Source](https://github.com/starforcraft/Cable-Tiers/issues/34)

**Comment by derrickmehaffy** [comment] 2023-10-28 02:18
Technically the root cause is from RS Core itself but they can't fix it because it would be a breaking change in 1.19 for add-on mods, they fixed in the 1.20 version: https://github.com/refinedmods/refinedstorage/issues/3449

**Closed** 2023-11-12 11:45 UTC

**Comment by SkeletonWhite** [comment] 2024-01-31 14:01
@marco3102 Hello, I noticed that you mentioned in another closed issue that the problem could be fixed through FTB Chunks settings. Could you please provide specific details on how to configure this setting?

**Comment by marco3102** [comment] 2024-01-31 14:15
@SkeletonWhite Its been a while since I played Minecraft.
I think it had something to do with allowing Fake Players to change Block statuses.
Look for something like that.
unclaiming chunks should also work.
