### ISSUE TITLE
Create mixer wastes ATM ore hammer.

### ISSUE THREAD

**Issue by Tenirrr** [AllTheMods/ATM-8#1538] opened 2023-07-08 11:43 UTC
I play on 1.0.21b on server. In previous versions, the hammer was left after making the recipe in the mixer. If you wanted to process e.g. copper ore, you would get two powders from one ore and one hammer. The hammer was left in the mixer.
Now disappears after doing literally one item. If you throw a whole stack of ore and a hammer into the mixer, only two powders will be made and the hammer will disappear.

Like in this video: https://www.youtube.com/watch?v=NkKnOIdz0Bg
but in my case hammer disappears after make 2 powders.

**Comment by Tenirrr** [comment] 2023-07-08 11:45
P.S. How to fix it?

**Comment by Mitchell5200** [comment] 2023-07-08 12:12
Duplicate of #1470 and #1500.
no known fixes at this stage

**Closed by Mitchell5200** 2023-07-08 12:12 UTC
Labels: duplicate
