### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by DevourHearts** [AllTheMods/ATM-8#649] opened 2023-01-12 01:37 UTC
[crash-2023-01-11_19.31.36-client.txt](https://github.com/AllTheMods/ATM-8/files/10397321/crash-2023-01-11_19.31.36-client.txt)

Can anyone help me figure out why I keep crashing? It has been the same error for 2 weeks now. I can't even play and it is very frustrating. Would love some more direction as to why I keep crashing. I have tried to read over the crash report to see if anything stands out but reading these things can get a bit confusing. When I have Googled this type of crash, all I have come up with is resource packs or shaders. Not sure how accurate that is.

**Comment by tunse80** [comment] 2023-01-12 21:05
I have been crashing a lot lately as well (I think it's been worse after the last update?). I've gotten 3 CTD's just this evening. The last one had this error message too. I'll leave my crash report here in case it helps (my other 2 CTD's were "Ticking Entity").

[crash-2023-01-12_21.58.20-client.txt](https://github.com/AllTheMods/ATM-8/files/10405954/crash-2023-01-12_21.58.20-client.txt)

**Comment by tunse80** [comment] 2023-01-16 12:36
... and another one. Please let me know if you need any more info or if anyone know how to potentially fix this. The crash log is attached.

[crash-2023-01-16_13.34.04-server.txt](https://github.com/AllTheMods/ATM-8/files/10425804/crash-2023-01-16_13.34.04-server.txt)

**Comment by tunse80** [comment] 2023-01-18 10:04
Yup, it seems as if something is causing problems, I just had another CTD with this error code. Unfortunately, I don't understand the crashlog but I hope it can be of use. :(

[crash-2023-01-18_10.57.42-client.txt](https://github.com/AllTheMods/ATM-8/files/10444560/crash-2023-01-18_10.57.42-client.txt)

**Comment by Mitchell5200** [comment] 2023-01-18 10:27
Mod at fault identified, and mod dev contacted, 
Duplicate of #307, #447, #553, #580, #649

**Comment by tunse80** [comment] 2023-01-18 16:40
Awesome, thanks a lot!

**Comment by DevourHearts** [comment] 2023-01-18 23:00
Yes thank you! I haven't been able to play because of the crashing. It really is random, could take a couple of hours or just a few mins and I crash again. I had no issues until I got further and further into the mod pack. I do have the Ars mage light around my base, first time I really have dove into Ars. I saw the comments about Ars mage lights, so figured I would mention it. I have not touch Evil Craft at all, I usually don't. The crash usually happens when I am in a loaded chunk. I do have a handful of compact machines that are loaded.

**Comment by ChooseJake** [comment] 2023-01-26 06:26
Nope. Issue still present in 1.0.9. As earlier there is no crash log

**Comment by Mitchell5200** [comment] 2023-01-26 06:34
yes, sorry, we falsely believed it was fixed, further investigation has pointed at evilcraft again, and another modder found it to be the true cause for 90% of the issues, the information has been passed on and hopefully it will be fixed soon
https://github.com/CyclopsMC/EvilCraft/issues/961

I'm also going to Pin this issue as it's clearly still active despite our previous information

**Comment by ChooseJake** [comment] 2023-01-26 06:45
No problem. It did generate a crash log btw I was just blind.
[crash-2023-01-12_13.51.06-client.txt](https://github.com/AllTheMods/ATM-8/files/10506927/crash-2023-01-12_13.51.06-client.txt)

**Comment by ChooseJake** [comment] 2023-02-03 11:16
This seems to be fixed as of the last patch. Haven't had any issues since

**Comment by Mitchell5200** [comment] 2023-02-14 08:11
Solved post 1.0.10, closing

**Closed by Mitchell5200** 2023-02-14 08:11 UTC
Labels: bug, Mod issue
