### ISSUE TITLE
connection lost while trying to play on LAN with family

### ISSUE THREAD

**Issue by jokerjosh1** [AllTheMods/ATM-8#444] opened 2022-12-17 23:00 UTC
every time me or my wife try to join one anothers world it gives us the same connection lost, Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException. Please help!!!!

**Comment by P0kys** [comment] 2022-12-17 23:08
As pinned at the top of the issues page, LAN is currently not working for ATM 8. You need to run a server to play MP

**Comment by Mitchell5200** [comment] 2022-12-19 10:06
Duplicate of #23 , Closing

**Closed by Mitchell5200** 2022-12-19 10:06 UTC
Labels: duplicate
