### ISSUE TITLE
EvilCraft crashing Minecraft possibly due to failure in spawning blood

### ISSUE THREAD

**Issue by cl0ck-byte** [AllTheMods/ATM-8#139] opened 2022-10-19 21:17 UTC
### [User no. 1's crash log](https://mclo.gs/uqAoG7W)

_ATM version is 0.1.5_
Player no. 1 killed a glow squid and crashed. Possibly because of dropped ink sack item that blocked spawning of EvilCraft's blood stain block?

### [User no. 2's crash log](https://mclo.gs/JBGUvKV)

_Note that it's ATM version 0.1.3_
Player no. 2 is unable to describe what exactly is happening, says that crashes occur randomly, independent of their actions.
They didn't kill any mobs during the time when crash occured. 

The only thing that could be useful is that it's happening in one particular area, so there might be some room for bats to spawn, and one could suffocate in a wall while being on the same X/Y/Z level as where blood wanted to spawn (Or just another bat in the same area), but that's probably next to impossible. 

More crash logs from the same user: [no 3; glowing ink sac](https://mclo.gs/wxmD5MM), [no 4; another bat](https://mclo.gs/Yz80m9h), [no 5; and another bat](https://mclo.gs/xHT46l7) and [probably unrelated crash](https://mclo.gs/8vMBoYv) mentioning Create's Flywheel renderer/engine from the same day, same exception description but there's no mention about EvilCraft.

Something I noticed is that bats tend to spawn at y level between 2 and 3 and aren't spread out as much, so there might be a structure that's killing them?

Edit: [Here are pictures of that place](https://imgur.com/a/cITavLQ) and [all player locations on the map](https://i.imgur.com/AxvtchT.png) marked with waypoints when they crashed due to a bat. My theory is that bats die on the pointed dripstone and EvilCraft tries to spawn blood and fails.

_Bug wasn't reported to EvilCraft's issue tracker yet due to their policy regarding bugs that occur within other modpacks._

**Comment by Mitchell5200** [comment] 2023-01-18 14:37
Mod at fault identified, and mod dev contacted, 
Duplicate of #307, #447, #553, #580, #649
Note, it's not Evilcraft at fault in these crashes

**Closed by Mitchell5200** 2023-01-18 14:37 UTC
Labels: Mod issue
