### ISSUE TITLE
SkulkSnapper Summon Causes Crash

### ISSUE THREAD

**Issue by aaronaustin0** [AllTheMods/ATM-8#481] opened 2022-12-21 02:07 UTC
Player uses Ank of Pray on Grave with soul receptacle for Skulk Snapper. 

As soon as ank is used, whole server crashes. 
Can't naturally stop the server. Always have to force close and it rolls back a few minutes. 

Crash log attached: 
[crash-2022-12-20_20.57.27-server.txt](https://github.com/AllTheMods/ATM-8/files/10273937/crash-2022-12-20_20.57.27-server.txt)

**Comment by Kaidavali** [comment] 2023-01-01 15:25
Getting the same issue here too. Happened in a place all players are located so as soon as anyone loads in the server dies, any known fix for this?

Crash log:
[crash-2023-01-01_15.16.01-server.txt](https://github.com/AllTheMods/ATM-8/files/10328992/crash-2023-01-01_15.16.01-server.txt)

**Comment by Mitchell5200** [comment] 2023-03-16 06:35
Duplicate of #370, known by the devs

**Closed** 2023-03-16 06:35 UTC
Labels: bug, duplicate, Mod issue
